name: deno-next-showcase

services:
  app:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./ops/docker/Dockerfile
      target: runner
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
